version: '3.8'
services:
#  back-end-bloom-api:
#    container_name: back-end-bloom-api
#    image: registry.gitlab.com/bitstrive/bpr/back-end:latest
#    ports:
#      - "8000:8080"
#    restart: always
#    environment:
#      KEYCLOAK_AUTHSERVERURL: "http://keycloak:8100/"
  keycloak:
    container_name: keycloak
    image: loh9
    ports:
      - "8100:8100"
      - "8443:8443"
    environment:
#      KC_HOSTNAME: "keycloak"
#      KC_HOSTNAME_STRICT: "false"
#      KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
      KC_HTTP_ENABLED: "true"
      KC_HTTP_PORT: "8100"
    command:
      - start --optimized
#networks:
#  default:
#    name: bloom-network

#  docker-compose up --force-recreate --build